# Generated by Django 3.1.2 on 2021-12-04 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='date_of_submission',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
