# Generated by Django 3.2.7 on 2021-11-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_submission_marks_obtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
