# Generated by Django 3.2.7 on 2021-12-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211204_2120'),
        ('users', '0003_submission_date_of_submission'),
    ]

    operations = [
    ]
