# Generated by Django 3.2.7 on 2021-12-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20211205_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='date_of_submission',
        ),
    ]
