# Generated by Django 3.1.2 on 2021-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_of_question',
            field=models.IntegerField(default=5),
        ),
    ]
