# Generated by Django 3.2.7 on 2021-12-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_question_id'),
        ('base', '0003_alter_question_id'),
    ]

    operations = [
    ]
